development:
  adapter: postgresql
  encoding: unicode
  database: piperspage_development
  pool: 5
  username: piperspage
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: piperspage_test
  pool: 5
  username: piperspage
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: piperspage_production
  pool: 5
  username: piperspage
  password:
